In [2]:
import yfinance as yf

In [3]:
ticker = yf.Ticker("AAPL")
print(ticker.info)

{'address1': 'One Apple Park Way', 'city': 'Cupertino', 'state': 'CA', 'zip': '95014', 'country': 'United States', 'phone': '(408) 996-1010', 'website': 'https://www.apple.com', 'industry': 'Consumer Electronics', 'industryKey': 'consumer-electronics', 'industryDisp': 'Consumer Electronics', 'sector': 'Technology', 'sectorKey': 'technology', 'sectorDisp': 'Technology', 'longBusinessSummary': 'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. The company offers iPhone, a line of smartphones; Mac, a line of personal computers; iPad, a line of multi-purpose tablets; and wearables, home, and accessories comprising AirPods, Apple Vision Pro, Apple TV, Apple Watch, Beats products, and HomePod, as well as Apple branded and third-party accessories. It also provides AppleCare support and cloud services; and operates various platforms, including the App Store that allow customers to discover and download applications and digital content, such as books, music, video, games, and podcasts, as well as advertising services include third-party licensing arrangements and its own advertising platforms. In addition, the company offers various subscription-based services, such as Apple Arcade, a game subscription service; Apple Fitness+, a personalized fitness service; Apple Music, which offers users a curated listening experience with on-demand radio stations; Apple News+, a subscription news and magazine service; Apple TV, which offers exclusive original content and live sports; Apple Card, a co-branded credit card; and Apple Pay, a cashless payment service, as well as licenses its intellectual property. The company serves consumers, and small and mid-sized businesses; and the education, enterprise, and government markets. It distributes third-party applications for its products through the App Store. The company also sells its products through its retail and online stores, and direct sales force; and third-party cellular network carriers and resellers. The company was formerly known as Apple Computer, Inc. and changed its name to Apple Inc. in January 2007. Apple Inc. was founded in 1976 and is headquartered in Cupertino, California.', 'fullTimeEmployees': 150000, 'companyOfficers': [{'maxAge': 1, 'name': 'Mr. Timothy D. Cook', 'age': 64, 'title': 'CEO & Director', 'yearBorn': 1961, 'fiscalYear': 2025, 'totalPay': 16759518, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Kevan  Parekh', 'age': 53, 'title': 'Senior VP & CFO', 'yearBorn': 1972, 'fiscalYear': 2025, 'totalPay': 4034174, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Sabih  Khan', 'age': 58, 'title': 'Senior VP & Chief Operating Officer', 'yearBorn': 1967, 'fiscalYear': 2025, 'totalPay': 5021905, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Ms. Katherine L. Adams', 'age': 61, 'title': 'Senior VP, General Counsel & Secretary', 'yearBorn': 1964, 'fiscalYear': 2025, 'totalPay': 5022482, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': "Ms. Deirdre  O'Brien", 'age': 58, 'title': 'Senior Vice President of Retail & People', 'yearBorn': 1967, 'fiscalYear': 2025, 'totalPay': 5037867, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Ben  Borders', 'age': 44, 'title': 'Principal Accounting Officer', 'yearBorn': 1981, 'fiscalYear': 2025, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Suhasini  Chandramouli', 'title': 'Director of Investor Relations', 'fiscalYear': 2025, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Ms. Kristin Huguet Quayle', 'title': 'Vice President of Worldwide Communications', 'fiscalYear': 2025, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Greg  Joswiak', 'title': 'Senior Vice President of Worldwide Marketing', 'fiscalYear': 2025, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Adrian  Perica', 'age': 51, 'title': 'Vice President of Corporate Development', 'yearBorn': 1974, 'fiscalYear': 2025, 'exercisedValue': 0, 'unexercisedValue': 0}], 'auditRisk': 7, 'boardRisk': 1, 'compensationRisk': 3, 'shareHolderRightsRisk': 1, 'overallRisk': 1, 'governanceEpochDate': 1769904000, 'compensationAsOfEpochDate': 1767139200, 'irWebsite': 'http://investor.apple.com/', 'executiveTeam': [], 'maxAge': 86400, 'priceHint': 2, 'previousClose': 275.5, 'open': 275.6, 'dayLow': 260.18, 'dayHigh': 275.72, 'regularMarketPreviousClose': 275.5, 'regularMarketOpen': 275.6, 'regularMarketDayLow': 260.18, 'regularMarketDayHigh': 275.72, 'dividendRate': 1.04, 'dividendYield': 0.38, 'exDividendDate': 1770595200, 'payoutRatio': 0.1304, 'fiveYearAvgDividendYield': 0.52, 'beta': 1.107, 'trailingPE': 33.088497, 'forwardPE': 28.172852, 'volume': 71430852, 'regularMarketVolume': 71430852, 'averageVolume': 47980221, 'averageVolume10days': 62286820, 'averageDailyVolume10Day': 62286820, 'bid': 261.57, 'ask': 261.74, 'bidSize': 4, 'askSize': 2, 'marketCap': 3846888226816, 'fiftyTwoWeekLow': 169.21, 'fiftyTwoWeekHigh': 288.62, 'allTimeHigh': 288.62, 'allTimeLow': 0.049107, 'priceToSalesTrailing12Months': 8.830895, 'fiftyDayAverage': 268.5108, 'twoHundredDayAverage': 239.5783, 'trailingAnnualDividendRate': 1.03, 'trailingAnnualDividendYield': 0.0037386569, 'currency': 'USD', 'tradeable': False, 'enterpriseValue': 4068255989760, 'profitMargins': 0.27037, 'floatShares': 14655594816, 'sharesOutstanding': 14681140000, 'sharesShort': 116854414, 'sharesShortPriorMonth': 112732788, 'sharesShortPreviousMonthDate': 1767139200, 'dateShortInterest': 1769731200, 'sharesPercentSharesOut': 0.008, 'heldPercentInsiders': 0.01702, 'heldPercentInstitutions': 0.65343004, 'shortRatio': 2.36, 'shortPercentOfFloat': 0.008, 'impliedSharesOutstanding': 14697926000, 'bookValue': 5.998, 'priceToBook': 43.63621, 'lastFiscalYearEnd': 1758931200, 'nextFiscalYearEnd': 1790467200, 'mostRecentQuarter': 1766793600, 'earningsQuarterlyGrowth': 0.159, 'netIncomeToCommon': 117776998400, 'trailingEps': 7.91, 'forwardEps': 9.29015, 'lastSplitFactor': '4:1', 'lastSplitDate': 1598832000, 'enterpriseToRevenue': 9.339, 'enterpriseToEbitda': 26.607, '52WeekChange': 0.14064503, 'SandP52WeekChange': 0.13514149, 'lastDividendValue': 0.26, 'lastDividendDate': 1770595200, 'quoteType': 'EQUITY', 'currentPrice': 261.73, 'targetHighPrice': 350.0, 'targetLowPrice': 205.0, 'targetMeanPrice': 293.06952, 'targetMedianPrice': 300.0, 'recommendationMean': 1.95745, 'recommendationKey': 'buy', 'numberOfAnalystOpinions': 41, 'totalCash': 66907000832, 'totalCashPerShare': 4.557, 'ebitda': 152901992448, 'totalDebt': 90509000704, 'quickRatio': 0.845, 'currentRatio': 0.974, 'totalRevenue': 435617005568, 'debtToEquity': 102.63, 'revenuePerShare': 29.305, 'returnOnAssets': 0.24377, 'returnOnEquity': 1.5202099, 'grossProfits': 206157004800, 'freeCashflow': 106312753152, 'operatingCashflow': 135471996928, 'earningsGrowth': 0.183, 'revenueGrowth': 0.157, 'grossMargins': 0.47325, 'ebitdaMargins': 0.35099998, 'operatingMargins': 0.35374, 'financialCurrency': 'USD', 'symbol': 'AAPL', 'language': 'en-US', 'region': 'US', 'typeDisp': 'Equity', 'quoteSourceName': 'Nasdaq Real Time Price', 'triggerable': True, 'customPriceAlertConfidence': 'HIGH', 'fiftyDayAverageChange': -6.780792, 'fiftyDayAverageChangePercent': -0.025253331, 'twoHundredDayAverageChange': 22.151718, 'twoHundredDayAverageChangePercent': 0.09246129, 'sourceInterval': 15, 'exchangeDataDelayedBy': 0, 'averageAnalystRating': '2.0 - Buy', 'cryptoTradeable': False, 'corporateActions': [], 'postMarketTime': 1770937604, 'regularMarketTime': 1770930002, 'exchange': 'NMS', 'messageBoardId': 'finmb_24937', 'exchangeTimezoneName': 'America/New_York', 'exchangeTimezoneShortName': 'EST', 'gmtOffSetMilliseconds': -18000000, 'market': 'us_market', 'esgPopulated': False, 'regularMarketChangePercent': -4.998181, 'regularMarketPrice': 261.73, 'shortName': 'Apple Inc.', 'longName': 'Apple Inc.', 'hasPrePostMarketData': True, 'firstTradeDateMilliseconds': 345479400000, 'postMarketChangePercent': 0.103155546, 'postMarketPrice': 262.0, 'postMarketChange': 0.269989, 'regularMarketChange': -13.769989, 'regularMarketDayRange': '260.18 - 275.72', 'fullExchangeName': 'NasdaqGS', 'averageDailyVolume3Month': 47980221, 'fiftyTwoWeekLowChange': 92.520004, 'fiftyTwoWeekLowChangePercent': 0.5467762, 'fiftyTwoWeekRange': '169.21 - 288.62', 'fiftyTwoWeekHighChange': -26.889984, 'fiftyTwoWeekHighChangePercent': -0.09316743, 'fiftyTwoWeekChangePercent': 14.064503, 'dividendDate': 1770854400, 'earningsTimestamp': 1769720400, 'earningsTimestampStart': 1777582800, 'earningsTimestampEnd': 1777582800, 'earningsCallTimestampStart': 1769724000, 'earningsCallTimestampEnd': 1769724000, 'isEarningsDateEstimate': True, 'epsTrailingTwelveMonths': 7.91, 'epsForward': 9.29015, 'epsCurrentYear': 8.4744, 'priceEpsCurrentYear': 30.884785, 'marketState': 'POST', 'displayName': 'Apple', 'trailingPegRatio': 2.4877}

In [4]:
history = ticker.history(period="1y")
history

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-02-13 00:00:00-05:00,235.881911,241.288340,234.547730,240.481857,53614100,0.00,0.0
2025-02-14 00:00:00-05:00,240.203105,244.484449,239.944239,243.538574,40896200,0.00,0.0
2025-02-18 00:00:00-05:00,243.090500,244.116029,240.790527,243.409119,48822500,0.00,0.0
2025-02-19 00:00:00-05:00,243.598278,244.942410,242.104787,243.807358,32204200,0.00,0.0
2025-02-20 00:00:00-05:00,243.877062,245.709073,243.229873,244.763199,32316900,0.00,0.0
...,...,...,...,...,...,...,...
2026-02-06 00:00:00-05:00,276.860920,280.647386,276.671095,277.859985,50453400,0.00,0.0
2026-02-09 00:00:00-05:00,277.910004,278.200012,271.700012,274.619995,44623400,0.26,0.0
2026-02-10 00:00:00-05:00,274.890015,275.369995,272.940002,273.679993,34376900,0.00,0.0
2026-02-11 00:00:00-05:00,274.700012,280.179993,274.450012,275.500000,51931300,0.00,0.0
2026-02-12 00:00:00-05:00,275.600006,275.720001,260.179993,261.730011,71430852,0.00,0.0

In [6]:
history = ticker.history(period="1mo")
history

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2026-01-13 00:00:00-05:00,258.478130,261.565238,258.148452,260.805939,45730800,0.00,0.0
2026-01-14 00:00:00-05:00,259.247418,261.575257,256.470018,259.716980,40019400,0.00,0.0
2026-01-15 00:00:00-05:00,260.406319,260.795969,256.809678,257.968597,39388600,0.00,0.0
2026-01-16 00:00:00-05:00,257.658902,258.657967,254.691677,255.291122,72142800,0.00,0.0
2026-01-20 00:00:00-05:00,252.493737,254.551809,243.192443,246.469376,80267500,0.00,0.0
2026-01-21 00:00:00-05:00,248.467509,251.324836,244.950795,247.418488,54641700,0.00,0.0
2026-01-22 00:00:00-05:00,248.967040,250.765360,247.918018,248.117844,39708300,0.00,0.0
2026-01-23 00:00:00-05:00,247.088808,249.176850,244.451261,247.808121,41689000,0.00,0.0
2026-01-26 00:00:00-05:00,251.244900,256.320153,249.566478,255.171234,55969200,0.00,0.0
2026-01-27 00:00:00-05:00,258.927717,261.705117,257.968592,258.028534,49648300,0.00,0.0
2026-01-28 00:00:00-05:00,257.409147,258.618008,254.272083,256.200287,41288000,0.00,0.0
2026-01-29 00:00:00-05:00,257.758807,259.407258,254.172166,258.038544,67253000,0.00,0.0
2026-01-30 00:00:00-05:00,254.931443,261.655147,251.944233,259.237427,92443400,0.00,0.0
2026-02-02 00:00:00-05:00,259.786917,270.237131,258.967677,269.757599,73913400,0.00,0.0
2026-02-03 00:00:00-05:00,268.948351,271.625839,267.359811,269.228088,64394700,0.00,0.0
2026-02-04 00:00:00-05:00,272.035451,278.689229,272.035451,276.231506,90545700,0.00,0.0
2026-02-05 00:00:00-05:00,277.869995,279.238709,272.974582,275.652069,52977400,0.00,0.0
2026-02-06 00:00:00-05:00,276.860920,280.647386,276.671095,277.859985,50453400,0.00,0.0
2026-02-09 00:00:00-05:00,277.910004,278.200012,271.700012,274.619995,44623400,0.26,0.0
2026-02-10 00:00:00-05:00,274.890015,275.369995,272.940002,273.679993,34376900,0.00,0.0
2026-02-11 00:00:00-05:00,274.700012,280.179993,274.450012,275.500000,51931300,0.00,0.0
2026-02-12 00:00:00-05:00,275.600006,275.720001,260.179993,261.730011,71430852,0.00,0.0